# -*- coding: utf-8 -*-
"""FaceMaskDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsn7ZjfA4X0v9KmISLJ7ieDrlzaCLAFo
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from PIL import Image
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

from google.colab import drive
drive.mount('/content/drive')

base_dir = '/content/drive/MyDrive/dataset'

with_mask_path = os.path.join(base_dir, 'with_mask')
without_mask_path = os.path.join(base_dir, 'without_mask')

with_mask_files = os.listdir(with_mask_path)
without_mask_files = os.listdir(without_mask_path)

print('Number of with mask images:', len(with_mask_files))
print('Number of without mask images:', len(without_mask_files))

with_mask_labels = [1] * len(with_mask_files)
without_mask_labels = [0] * len(without_mask_files)
labels = with_mask_labels + without_mask_labels

data = []

for img_file in with_mask_files:
    image = Image.open(os.path.join(with_mask_path, img_file))
    image = image.resize((128,128))
    image = image.convert('RGB')
    image = np.array(image)
    data.append(image)

for img_file in without_mask_files:
    image = Image.open(os.path.join(without_mask_path, img_file))
    image = image.resize((128,128))
    image = image.convert('RGB')
    image = np.array(image)
    data.append(image)

X = np.array(data)
Y = np.array(labels)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

X_train_scaled = X_train / 255
X_test_scaled = X_test / 255

num_of_classes = 2

model = keras.Sequential([
    keras.layers.Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(128,128,3)),
    keras.layers.MaxPooling2D(pool_size=(2,2)),

    keras.layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    keras.layers.MaxPooling2D(pool_size=(2,2)),

    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(num_of_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc'])

history = model.fit(X_train_scaled, Y_train, validation_split=0.1, epochs=5)

loss, accuracy = model.evaluate(X_test_scaled, Y_test)
print('Test Accuracy =', accuracy)

model.save('mask_prediction_model.keras')
print("✅ Model saved successfully!")

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='validation loss')
plt.legend()
plt.title('Training Loss')

plt.subplot(1,2,2)
plt.plot(history.history['acc'], label='train accuracy')
plt.plot(history.history['val_acc'], label='validation accuracy')
plt.legend()
plt.title('Training Accuracy')
plt.show()

def predict_mask(image_path):
    input_image = cv2.imread(image_path)
    plt.imshow(cv2.cvtColor(input_image, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.show()

    input_image_resized = cv2.resize(input_image, (128,128))
    input_image_scaled = input_image_resized / 255
    input_image_reshaped = np.reshape(input_image_scaled, [1,128,128,3])

    input_prediction = model.predict(input_image_reshaped)
    input_pred_label = np.argmax(input_prediction)

    result = 'The person is wearing a mask' if input_pred_label == 1 else 'The person is NOT wearing a mask'
    print(result)

while True:
    try:
        image_path = input('\nEnter path of the image to predict (or "q" to quit): ')
        if image_path.lower() == 'q':
            break
        predict_mask(image_path)
    except Exception as e:
        print(f"Error processing image: {e}")